# Generated by Django 4.2.2 on 2023-07-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='avaible',
            new_name='available',
        ),
    ]
